version: '3.8'

services:
    postgresql:
        image: postgres:16
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD:
            POSTGRES_HOST_AUTH_METHOD: trust
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - 1997:5432